name: "Build Ubuntu Image and Rootfs"
author: "https://github.com/ophub/flippy-ubuntu-actions"
description: "Automated Ubuntu image and rootfs builder for Rockchip devices"
inputs:
  mode:
    description: "Select the build script to execute."
    required: false
    default: "flippy"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd "${GITHUB_ACTION_PATH}"
        ./make_actions.sh

branding:
  icon: "terminal"
  color: "gray-dark"
